[package]
name = "ai-quota-desktop"
version = "0.1.0"
description = "Windows tray quota monitor"
authors = ["kongdd"]
edition = "2021"

[lib]
name = "ai_quota_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-http = { version = "=2.5.9", features = ["unsafe-headers"] }

[features]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
panic = "abort"
strip = true
